/** Generated by scripts/sync-catalog-redirects.mjs — do not edit. */
export const CATALOG_REDIRECT_ENTRIES = [
  {
    "from": "/songs/the-seven-sutras-of-banana",
    "to": "/songs/seven-sutras-gone-banana/",
    "reason": "L-383 rename"
  }
] as const
