/** Generated by scripts/sync-catalog-redirects.mjs — do not edit. */
export const CATALOG_REDIRECT_ENTRIES = [
  {
    "from": "/songs/broken-whole-encore",
    "to": "/songs/broken-whole",
    "reason": "L-423 to L-346"
  },
  {
    "from": "/songs/serial-blowers-vol2",
    "to": "/songs/serial-blowers",
    "reason": "L-425 to L-216"
  },
  {
    "from": "/songs/the-seven-sutras-of-banana",
    "to": "/songs/seven-sutras-gone-banana/",
    "reason": "L-383 rename"
  }
] as const
